env:
  RCLONECONFIG_DRIVE: "ENCRYPTED[!a7be560ba6337808f79d585d09df2528f52962f08a925c86df7f5f34932f78d837f361cf2984949e68cd60a8b7ba1a5f!]"
  TG_TOKEN: "ENCRYPTED[!1121414bed0cc4dc1f936eaf255035f008bbec4783d13a5460506e22677904394b9df28714de5f618cdabeb71b27b78e!]"
  TG_CHAT_ID: "ENCRYPTED[!4b6791fedaed0439126b06a8e7e51b4d41f484f30145e4891399e3e251c377ed4864f1fb766d0dc51bddc9d6b4fb66a8!]"
  WORKDIR: "/tmp"
  EMAIL: "ENCRYPTED[!a6b04e6d20a842588543c86b7a0f6ca8be6532d42f79e989b75caca8edd01c4273fab375405a8386338696a7091627da!]"
  CIRRUS_CLONE_DEPTH: "1"
  credentials: "ENCRYPTED[!41ea26b6d46ace395c3bc825472bafe065de7cba199e962e219cf139bfbc107fe97915a98f4a6f060836e31a3403bfe0!]"

task:
  name: "Sync"
  only_if: $CIRRUS_REPO_OWNER == 'monu3k'
  timeout_in: 120m
  container:
    image: zacky46/build:22.04
    cpu: 8
    memory: 32G

  Load-Ccache_background_script:
     - ./script/load_ccache.sh

  Sync-rom_script:
     - git config --global user.name "Monu"
     - git config --global user.email "$EMAIL"
     - echo "$credentials" > ~/.git-credentials
     - git config --global credential.helper store --file=~/.git-credentials
     - ./script/sync.sh
     
  Build-rom_script:
     - ./script/building.sh
     
  Ccache-info_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Upload-build_script:
     - ./script/ziping.sh

#end
